### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by jsuator** [SPC-universe/spc-opensource#1]
Hi , i am testing the SPC FIT PULSE on  android version  and can not get any data . 
If i sincronize the ofical app with the SPC FIT PULSE , the spc-opensource work , but i do no want to use two apps to get the data.

09-07 12:36:41.245  12930-13015/com.spc.spcfitsdk D/BluetoothGatt﹕ onGetService() - Device=DA:E4:B1:BE:13:5C UUID=00001800-0000-1000-8000-00805f9b34fb
09-07 12:36:41.255  12930-12943/com.spc.spcfitsdk D/BluetoothGatt﹕ onGetService() - Device=DA:E4:B1:BE:13:5C UUID=00001801-0000-1000-8000-00805f9b34fb
09-07 12:36:41.255  12930-12942/com.spc.spcfitsdk D/BluetoothGatt﹕ onGetService() - Device=DA:E4:B1:BE:13:5C UUID=0000180a-0000-1000-8000-00805f9b34fb
09-07 12:36:41.255  12930-13015/com.spc.spcfitsdk D/BluetoothGatt﹕ onGetService() - Device=DA:E4:B1:BE:13:5C UUID=0000fff0-0000-1000-8000-00805f9b34fb
09-07 12:36:41.255  12930-12943/com.spc.spcfitsdk D/BluetoothGatt﹕ onGetCharacteristic() - Device=DA:E4:B1:BE:13:5C UUID=00002a00-0000-1000-8000-00805f9b34fb
09-07 12:36:41.260  12930-12942/com.spc.spcfitsdk D/BluetoothGatt﹕ onGetCharacteristic() - Device=DA:E4:B1:BE:13:5C UUID=00002a01-0000-1000-8000-00805f9b34fb
09-07 12:36:41.260  12930-13015/com.spc.spcfitsdk D/BluetoothGatt﹕ onGetCharacteristic() - Device=DA:E4:B1:BE:13:5C UUID=00002a04-0000-1000-8000-00805f9b34fb
09-07 12:36:41.260  12930-12943/com.spc.spcfitsdk D/BluetoothGatt﹕ onGetCharacteristic() - Device=DA:E4:B1:BE:13:5C UUID=00002a05-0000-1000-8000-00805f9b34fb
09-07 12:36:41.260  12930-12942/com.spc.spcfitsdk D/BluetoothGatt﹕ onGetCharacteristic() - Device=DA:E4:B1:BE:13:5C UUID=00002a29-0000-1000-8000-00805f9b34fb
09-07 12:36:41.265  12930-13015/com.spc.spcfitsdk D/BluetoothGatt﹕ onGetCharacteristic() - Device=DA:E4:B1:BE:13:5C UUID=0000fff7-0000-1000-8000-00805f9b34fb
09-07 12:36:41.265  12930-12943/com.spc.spcfitsdk D/BluetoothGatt﹕ onGetCharacteristic() - Device=DA:E4:B1:BE:13:5C UUID=0000fff6-0000-1000-8000-00805f9b34fb
09-07 12:36:41.270  12930-12942/com.spc.spcfitsdk D/BluetoothGatt﹕ onGetDescriptor() - Device=DA:E4:B1:BE:13:5C UUID=00002902-0000-1000-8000-00805f9b34fb
09-07 12:36:41.270  12930-12942/com.spc.spcfitsdk D/BluetoothGatt﹕ onGetDescriptor() - Device=DA:E4:B1:BE:13:5C UUID=00002902-0000-1000-8000-00805f9b34fb
09-07 12:36:41.270  12930-12943/com.spc.spcfitsdk D/BluetoothGatt﹕ onSearchComplete() = Device=DA:E4:B1:BE:13:5C Status=0
09-07 12:36:41.270  12930-12943/com.spc.spcfitsdk D/BluetoothGatt﹕ setCharacteristicNotification() - uuid: 0000fff7-0000-1000-8000-00805f9b34fb enable: true
09-07 12:36:44.550  12930-12930/com.spc.spcfitsdk D/Activity Tracker﹕ startRealTimeMeterMode.
09-07 12:36:44.575  12930-12930/com.spc.spcfitsdk I/PASos﹕ Pasos
09-07 12:36:44.575  12930-12930/com.spc.spcfitsdk D/Activity Tracker﹕ getTargetSteps.
09-07 12:36:44.575  12930-12930/com.spc.spcfitsdk I/Calculos﹕ 75
09-07 12:36:44.575  12930-12930/com.spc.spcfitsdk D/BluetoothGatt﹕ writeCharacteristic() - uuid: 0000fff6-0000-1000-8000-00805f9b34fb
09-07 12:36:44.580  12930-13015/com.spc.spcfitsdk D/BluetoothGatt﹕ onCharacteristicWrite() - Device=DA:E4:B1:BE:13:5C UUID=0000fff6-0000-1000-8000-00805f9b34fb Status=0
09-07 12:36:44.580  12930-12930/com.spc.spcfitsdk D/Activity Tracker﹕ realTimeMeterModeResponse bytes: 75 : 00 : 00 : 00 : 00 : 00 : 00 : 00 : 00 : 00 : 00 : 00 : 00 : 00 : 00 : 75
09-07 12:36:44.580  12930-12930/com.spc.spcfitsdk D/Activity Tracker﹕ Steps: 0 Calories: 0 KM: 0
09-07 12:36:44.580  12930-12930/com.spc.spcfitsdk I/Calculos﹕ 9
09-07 12:36:44.580  12930-12930/com.spc.spcfitsdk D/BluetoothGatt﹕ writeCharacteristic() - uuid: 0000fff6-0000-1000-8000-00805f9b34fb
09-07 12:36:44.585  12930-12930/com.spc.spcfitsdk D/Activity Tracker﹕ realTimeMeterModeResponse bytes: 09 : 00 : 00 : 00 : 00 : 00 : 00 : 00 : 00 : 00 : 00 : 00 : 00 : 00 : 00 : 09
09-07 12:36:44.585  12930-12930/com.spc.spcfitsdk D/Activity Tracker﹕ Steps: 0 Calories: 0 KM: 0

**Comment by erlaitz-pixybit** [comment]
Hemos actualizado el repositorio con soporte para el dispositivo SPC FIT PULSE.

**Comment by ghost** [comment]
Hola, en iOS ocurre lo mismo, ¿se va a actualizar también? Gracias.

**Comment by falava** [comment]
@maitines Sí, estamos actualizando el ejemplo de iOS para demostrar la funcionalidad de seguridad en la pulsera.

Las respuestas a 0 se deben a que el móvil y el dispositivo deben acordar primero una clave de seguridad.

**Comment by falava** [comment]
@maitines Ya hemos actualizado el ejemplo de iOS y ahora te debería funcionar.

También hemos actualizado el proyecto a Xcode 7 e iOS 9, con un pequeño cambio.

En la pantalla FechaViewController está el ejemplo sobre cómo intercambiar una clave de seguridad con el dispositivo. La clave debería ser diferente para cada usuario, pero en el ejemplo es simplemente _123456_. El dispositivo siempre responde a todos los comandos con 0 si no se le guarda inicialmente una clave (una sola vez) y luego se le envía dicha clave como primer comando tras la conexión.

Cualquier cosa nos comentas.
